name: devgate-user-service
services:
  db:
    image: 'postgres:latest'
    env_file:
      - '../../.env'
    ports:
      - '5433:5432'
    networks:
      - app_network

networks:
  app_network:
    external: true